### ISSUE TITLE
Local card with Custom_updater config?

### ISSUE THREAD

**Issue by Tom-ahawk** [gadgetchnnel/lovelace-home-feed-card#1]
Hi. Nice card!

I store my Lovelace cards manually. How do I configure this card to be used with custom_updater?

custom_updater:
  track:
    - cards
  card_urls:
    -  ???
    - https://raw.githubusercontent.com/maykar/lovelace-swipe-navigation/master/tracker.json

**Comment by gadgetchnnel** [comment]
Try adding the following to the card_urls:

https://raw.githubusercontent.com/gadgetchnnel/lovelace-home-feed-card/master/custom_card.json

I've not actually tried it myself, but that file (needed for the ?track=true method to work), also appears to be the right format for tracking via card_urls).

Please let me know if it works, and I will update the README file to add that information.

**Comment by Tom-ahawk** [comment]
Thanks!

That did work. I didn’t have to "?track=true". I read somewhere that this is the default mode of custom_updater.
