### ISSUE TITLE
Alternating display on home feed card

### ISSUE THREAD

**Issue by geejayem99** [gadgetchnnel/lovelace-home-feed-card#15]
I have just updated from ha 0.97.2 to 0.98.1 (skipped 0.98.0) and now I've noticed the home feed card is flicking between this:

![Home-feed-a](https://user-images.githubusercontent.com/52344068/64061387-32cc2880-cc19-11e9-8dcb-c8e95500c08f.jpg)

and this:

![Home-feed-b](https://user-images.githubusercontent.com/52344068/64061389-411a4480-cc19-11e9-87e1-cc4a0e05b1ef.jpg)

Is it just me? I'm seeing it on Firefox 68.0.2 (64 bit) on win 10 but also on latest chrome on the same laptop as well as android tablets running chrome and on wallpanel. Home feed card is version 0.2.10 downloaded via HACS.

The card config looks like this:

![Home-feed-config](https://user-images.githubusercontent.com/52344068/64061424-cd2c6c00-cc19-11e9-840f-07862d864a5d.jpg)

and was working OK with 0.97.2  though in the past it does this just once when the page is first loaded or reloaded and settles to the regular display as in image 2. There's no regular frequency of the change but it's rarely staying on one 'screen' for more than a few seconds.

**Comment by gadgetchnnel** [comment]
Try the latest beta version of the card (0.2.11b3) which should fix this.
If you are using HACS You may need to enable Beta versions for the card ("show beta") on the "hamburger" menu on the card details. Otherwise you can download the beta from the Releases page.

**Comment by geejayem99** [comment]
That seems to have sorted it out. Thanks for the quick response :)
