### ISSUE TITLE
Not always shown in Home assistant app

### ISSUE THREAD

**Issue by isabellaalstrom** [gadgetchnnel/lovelace-home-feed-card#18]
Quite often I get "custom element doesn't exist: home-feed-card" in the Home Assistant Companion ios app. Clearing frontend cache usually fixes it, but that's a temporary fix. Maybe something is wrong with the loading order?

**Comment by isabellaalstrom** [comment]
It didn't show in Chrome on my pc now either, and then I managed to remember getting the error from the console:
`Uncaught SyntaxError: Identifier 'LitElement' has already been declared
    at lovelace-home-feed-card.js:1`

**Comment by gadgetchnnel** [comment]
I have done some refactoring of how it refers to LitElement, which may help with this.
This has been deployed to the latest beta (0.2.12b2).

**Comment by isabellaalstrom** [comment]
Thanks, this seems to have resolved my issues :)
