### ISSUE TITLE
max_item_count stopped working in 0.2.11

### ISSUE THREAD

**Issue by Juice2019** [gadgetchnnel/lovelace-home-feed-card#19]
Hi 

I can't get max_item_count working in the newest update, however if i switch back to 0.2.10 this works. 

Is there a fix? Or is it a removed feature. 

Thanks

**Comment by gadgetchnnel** [comment]
It appears that the logic for this was lost in the refactor to use LitElement. I have fixed this in the latest beta (0.2.12b2).

**Comment by Juice2019** [comment]
works thanks!
