### ISSUE TITLE
Request: Add a parameter to control end time for calendars

### ISSUE THREAD

**Issue by editter** [gadgetchnnel/lovelace-home-feed-card#21]
Can you add a config option so calendars can have an end time longer than 2 days out?

Maybe something like this?
```
const calendar_days = isNaN(this._config.calendar_days) ? 2 : parseInt(this._config.calendar_days);
const end = this.moment.utc().startOf('day').add(calendar_days, 'days').format("YYYY-MM-DDTHH:mm:ss");
```

**Comment by gadgetchnnel** [comment]
@editter This has now been added in the latest beta version (0.3.5b2). I have actually split it into two options **calendar_days_back** and **calendar_days_forward** so you have more flexibility over the range for which the events will be queries.

**Comment by gadgetchnnel** [comment]
Closing this as this feature is now in the latest release version
