### ISSUE TITLE
Add to the HACS repo

### ISSUE THREAD

**Issue by lights0123** [gadgetchnnel/lovelace-home-feed-card#3]
This repository can already be added as a [HACS](https://github.com/custom-components/hacs) custom repository with no changes, but it would be better if it was added to the HACS store. HACS is the replacement to the deprecated custom_updater.

**Comment by gadgetchnnel** [comment]
This should already be in the HACS store. It was added to the default repositories on 1st July. Are you not seeing it? If you added it via a custom repository, check whether this repository is still in your settings. If it isn't then I believe that means it is now picking it up from the default repositories.

**Comment by lights0123** [comment]
@gadgetchnnel Yep. I just had not upgraded HACS since.
