### ISSUE TITLE
Updated to latest beta - CUSTOM CARD DOES NOT EXIST

### ISSUE THREAD

**Issue by scfigg** [gadgetchnnel/lovelace-home-feed-card#30]
Have had this card in use for a while, and now having issues with it after updating to latest beta 3. Even after I use HACS to downgrade, and reboot/refresh page, I'm still having the issue:

Custom element doesn't exist: home-feed-card.

Any ideas? I made sure the module is setup correctly in the lovelace ui config.

**Comment by MarcoFranchi** [comment]
I have the some problem...

**Comment by gadgetchnnel** [comment]
@scfigg @MarcoFranchi This is an issue with HACS not downloading all the files the card requires. It is fixed in the latest Beta version of HACS, but I would advise waiting until there is a stable release.
The best workaround for now is to download the latest release from the Releases page and manually copy the files across (you need all of the Javascript files for it to work).

**Comment by mfabiani53** [comment]
Same here also with the 0.3.9

**Comment by gadgetchnnel** [comment]
@scfigg @MarcoFranchi @mfabiani53 Can you all please try the latest beta version (0.4.0b1)?
This has been refactored using Node JS and webpack, so it results in a single Javascript file. This means it shouldn't have the same issue when downloaded via HACS, and it should hopefully also make to code easier to maintain in future.

**Comment by scfigg** [comment]
Upgraded, and still having the same issue.

**Comment by gadgetchnnel** [comment]
@scfigg Can you please check a couple of things?

* What files are present in the folder after updating, and what are their sizes? The **lovelace-home-feed-card.js** should be approximately 300 KB, if it is smaller you may still have an old version
* Are there any errors in the Javascript console? It's possible that the refactoring could have caused issues on some systems, who that will help determine if that is the case.

If those seem fine, you may want to try a hard refresh in case it is just a caching issue.

**Comment by scfigg** [comment]
What would the path be for the javascript file on hassio? I'm having a brain fart for some reason and can't find it.

**Comment by gadgetchnnel** [comment]
@scfigg It should be /config/www/community/lovelace-home-feed-card/
(Where **/config** is the location where your configuration.yaml file is located)

**Comment by scfigg** [comment]
Weird - no files were in there, despite being installed in HACS. Folder wasn't even there. I 'uninstalled' from HACS, then reinstalled and saw the folder and files get created. It's working now.

**Comment by gadgetchnnel** [comment]
Closing now as this appears to be resolved in latest beta.
