### ISSUE TITLE
Transparency issue

### ISSUE THREAD

**Issue by tomlut** [gadgetchnnel/lovelace-home-feed-card#4]
Is there any way the styling used for the title can be set to support transparency?

This is the only card I'm having this issue with. There seems to be a hard coded white background to the title that is not respecting theme settings.

![Untitled](https://user-images.githubusercontent.com/10679300/61601116-5d6cae00-ac77-11e9-9a87-ebf513cba039.png)

**Comment by tomlut** [comment]
I removed lines 83 and 84 lines from the js file and it now displays as I would expect it to.
```
          	background: var(--ha-card-background, var(--paper-card-background-color, white));
          	opacity: 1.0;
```

**Comment by gadgetchnnel** [comment]
@tomlut Those lines were there because the feed is scrollable with a fixed header and, without them, the feed was visible through the header when scrolling (even with a non-transparent theme). I'll need to work out if there is a way to only do this when the background is non-transparent.

**Comment by tomlut** [comment]
I just generated a bunch of alerts and see what you mean:
![Untitled](https://user-images.githubusercontent.com/10679300/61620321-03d6a480-acb4-11e9-9354-389de9abd428.png)

Is it possible to make non-scrollable an option?

And have older messages progress up the list as newer ones are deleted?

**Comment by gadgetchnnel** [comment]
@tomlut Can you please try version 0.2.8b2 and see if this resolves this for you. The new version applies the scrollbars to just the section containing the feed rather than the whole card, which means it no longer needs to override the background colour and opacity on the header and should work better with custom themes.

**Comment by tomlut** [comment]
Hi Steven, I can confirm that v0.2.8b2 fixes the issue. Thank you for this great card and the rapid resolution of the issue.

![Annotation 2019-07-23 095447](https://user-images.githubusercontent.com/10679300/61672729-1bec0980-ad30-11e9-8d80-fa5dcecd87a1.png)
