### ISSUE TITLE
Device class ignored for entity state

### ISSUE THREAD

**Issue by joshtbernstein** [gadgetchnnel/lovelace-home-feed-card#40]
~~I'm not convinced this isn't an issue with the frontend, but thought I'd start here.~~ After updating to 0.109, the feed isn't showing the proper state based on an entity's device class:

![Screen Shot 2020-04-30 at 1 41 04 PM](https://user-images.githubusercontent.com/13294526/80757213-a2681f80-8ae8-11ea-9ba1-a6b06134d276.png)

**Comment by bramkragten** [comment]
Please see <https://developers.home-assistant.io/blog/2020/04/23/frontend-translations>

**Comment by gadgetchnnel** [comment]
Can you try with the latest beta 0.4.2b3 which has a fix for this?

**Comment by WhimsySpoon** [comment]
I can confirm that 0.4.2b3 fixes this issue.

**Comment by joshtbernstein** [comment]
@gadgetchnnel Somehow I missed your response. Like @WhimsySpoon said, the beta does fix this.

**Comment by gadgetchnnel** [comment]
Closing this as it is now confirmed as fixed.
