### ISSUE TITLE
On new event every Icons on the historic  for the same entity are replaced by the last entity icon. 

### ISSUE THREAD

**Issue by fre69** [gadgetchnnel/lovelace-home-feed-card#42]
Hi.
I use the card to display motions historic of a netatmo camera from a template sensor:
  - platform: template
    sensors: 
      netatmo_camera_template:
        friendly_name: "Camera chemin "
        entity_id: sensor.netatmo_camera_event
#        availability_template:  >-
#          {% if is_state('camera.netatmo_chemin', 'recording') %}
#            true
#          {% else %}
#            false
#          {% endif %}
        value_template:  >-
          {% if is_state('sensor.netatmo_camera_event', 'vehicle') %}
            Voiture
          {% elif is_state('sensor.netatmo_camera_event', 'human') %}
            Humain
          {% elif is_state('sensor.netatmo_camera_event', 'animal') %}
            Animal
          {% elif is_state('sensor.netatmo_camera_event', 'movement') %}
            Mouvement
          {% else %}
            unknown
          {% endif %}        
        entity_picture_template: >-
          {% if state_attr('sensor.netatmo_camera_event', 'data').vignette_url != None %}
            {{ state_attr('sensor.netatmo_camera_event', 'data').vignette_url }}
          {% endif %}
        icon_template:   >-
          {% if is_state('sensor.netatmo_camera_event', 'vehicle') %}
            mdi:car
          {% elif is_state('sensor.netatmo_camera_event', 'human') %}
            mdi:human-male
          {% elif is_state('sensor.netatmo_camera_event', 'animal') %}
            mdi:paw
          {% elif is_state('sensor.netatmo_camera_event', 'movement') %}
            mdi:tree
          {% endif %}
        attribute_templates:
          snapshot_url:   >-
            {% if state_attr('sensor.netatmo_camera_event', 'data').snapshot_url != None %}
              {{ state_attr('sensor.netatmo_camera_event', 'data').snapshot_url }}
            {% endif %}
          vignette_url:   >-
            {% if state_attr('sensor.netatmo_camera_event', 'data').vignette_url != None %}
              {{ state_attr('sensor.netatmo_camera_event', 'data').vignette_url }}
            {% endif %}
          message:   >-
            {% if state_attr('sensor.netatmo_camera_event', 'data').message != None %}
              {{ state_attr('sensor.netatmo_camera_event', 'data').message }}
            {% endif %}
![Before event](https://user-images.githubusercontent.com/17986918/83243370-1526f200-a19e-11ea-86b4-41397b134899.PNG)

After restart home assistant everything is ok but when a new event come every icons from the historic of the entity will be the same.

![After event](https://user-images.githubusercontent.com/17986918/83243396-1f48f080-a19e-11ea-9db8-c01bfc89e3c5.PNG)

Thanks for everything.

**Comment by gadgetchnnel** [comment]
I've just released a new Beta version (0.4.3b2) with a fix for this.

Can you please try it and let me know if it fixes it for you?

**Comment by fre69** [comment]
With this version Icons are ok, even after an event. Thank you.
But it doesn't use the entity_picture now, I have to delete my icon_template to show the entity_picture_template?

**Comment by fre69** [comment]
![After event](https://user-images.githubusercontent.com/17986918/83247991-adc07080-a1a4-11ea-80b5-40ea8b68a519.PNG)

**Comment by gadgetchnnel** [comment]
Yes, If there is an icon defined then this will override the entity_picture, so you would need to remove the icon_template if you want entity_picture to be used.

Edit: Please let me know if there are still issues after doing this, as it's possible that the fix I made doesn't pass the entity_picture from the history item, only the icon.

**Comment by fre69** [comment]
Thank you very much. Without icon it's working. I put icons for card witch doesn't display entity_picture but il will do another sensor for that.
Everything Ok.
