### ISSUE TITLE
Not handling ISO8601 unit properly

### ISSUE THREAD

**Issue by eavanvalkenburg** [gadgetchnnel/lovelace-home-feed-card#43]
According to the official docs, a sensor with device_class timestamp should have ISO8601 as the unit_of_measurement, however when I set that, it shows this:
![image](https://user-images.githubusercontent.com/13749212/86216618-9ba86800-bb7e-11ea-9fa7-a0dc86201abb.png)

This is from a custom component that I created, so I can change it, but would be good if the visual can just deal with that! This is on version v0.4.5.

**Comment by gadgetchnnel** [comment]
I've implemented a fix for this in the latest version (0.4.6) can you please try with that and let me know if it fixes it for you?

**Comment by eavanvalkenburg** [comment]
I am on .4.6, but still this: 
![image](https://user-images.githubusercontent.com/13749212/86442266-d1c82200-bd0d-11ea-8994-eb3ec2bf0c86.png)

**Comment by eavanvalkenburg** [comment]
The datatype is a datetime object

**Comment by eavanvalkenburg** [comment]
Never mind, it turns out that even though I rebooted my machine, I had to force reload the page before it picked up the change, now it looks like this:
![image](https://user-images.githubusercontent.com/13749212/86443224-464f9080-bd0f-11ea-9f8d-47f82779c698.png)
