### ISSUE TITLE
Installation via HACS "Custom element doesn't exist"

### ISSUE THREAD

**Issue by Morphy99** [gadgetchnnel/lovelace-home-feed-card#44]
I'm struggling to get this working, not sure if I've missed something but if I add a new custom card in lovelace as per the example I get this error:
bad indentation of a mapping entry at line 2, column 3: title: Home Feed ^
No card type found

If I remove the indentation next to title I get:
'Custom element doesn't exist: home-feed-card.'

Not sure it's installed correctly as it's in www\community\lovelace-home-feed-card and manual instructions suggest it should be in a custom-lovelace folder within www

**Comment by gadgetchnnel** [comment]
It seems that the file hasn't been added to your Lovelace resources. Can you please let me know:

* Did you use [HACS](https://hacs.xyz/) to install this or have you installed it manually?
* Do you edit your Lovelace through the UI (storage mode) or via YAML?

**Comment by Morphy99** [comment]
Yep, I had lovelace set to storage mode for some reason I can't remember now... It works ok without it so hopefully I don't need it set to that anymore.
And yes installed via HACS.
