### ISSUE TITLE
Show's only days to go with calendar event.

### ISSUE THREAD

**Issue by Jurgenn22** [gadgetchnnel/lovelace-home-feed-card#46]
@gadgetchnnel 
Hello,

Nice card, thanks for that.

Why does a calendar event only show days to go? I would like to see the date and time for each calendar event. Is that possible? However when I put the mouse on the days to go, a pop-up appears with the date and time of the event.

![image](https://user-images.githubusercontent.com/50082445/90405477-16343500-e0a4-11ea-8ffb-7212c722ee80.png)

![image](https://user-images.githubusercontent.com/50082445/90405551-35cb5d80-e0a4-11ea-9cab-06dbc5358069.png)

![image](https://user-images.githubusercontent.com/50082445/90408729-82b13300-e0a8-11ea-9265-bd6cbfe0261c.png)

**Comment by gadgetchnnel** [comment]
I've added a new option in version 0.6.2 named calendar_time_format  which controls how the calendar event timestamp should be formatted. Valid values are: relative, date, time and datetime. The default is "relative" which disiplays the time until the event, but setting it to "datetime" will give the date and time of the event.

For example:

    - type: 'custom:home-feed-card'
      calendars:
        - calendar.my_calendar
      calendar_time_format: datetime

**Comment by Jurgenn22** [comment]
@gadgetchnnel 
Fantastic, works perfectly.
Thanks for the update!
