### ISSUE TITLE
Display Persistent Notification Title

### ISSUE THREAD

**Issue by jazzyisj** [gadgetchnnel/lovelace-home-feed-card#48]
Am I missing something or is there not a way to display the title of a persistent notification?

![image](https://user-images.githubusercontent.com/44064559/92343828-cb01b680-f092-11ea-84c1-1fcaad5b4b5f.png)

![image](https://user-images.githubusercontent.com/44064559/92343868-e79dee80-f092-11ea-950b-b57aee334294.png)

**Comment by gadgetchnnel** [comment]
Sorry, I thought this was in the README, but you can do this with the show_notification_title option, like this:

```
type: 'custom:home-feed-card'
title: Notifications
show_notification_title: true
```

I've also updated the README now to add that option.
