### ISSUE TITLE
Request: Add support for binary sensor device classes

### ISSUE THREAD

**Issue by dummptyhummpty** [gadgetchnnel/lovelace-home-feed-card#5]
It would be awesome to support the sensor device classes [here](https://www.home-assistant.io/components/binary_sensor/) so that binary sensors show the correct state.

Ex, doors show on or off, but should show open or closed.

**Comment by gadgetchnnel** [comment]
Support for that is in beta (this was introduced in 0.2.8b1). If you use HACS you can use the **Show Beta** option in the "hamburger" menu when viewing the details for this card. Otherwise, you can manually download the betas from the [Releases](https://github.com/gadgetchnnel/lovelace-home-feed-card/releases) page.

**Comment by dummptyhummpty** [comment]
@gadgetchnnel Thanks for the quick response! I was able to upgrade to 0.2.8b2 (I'm using HACS so thanks for that tip), but it doesn't seem to be working for all my binary sensors. Happy to help with troubleshooting unless it's just something on my end.

**Comment by gadgetchnnel** [comment]
@dummptyhummpty Do you have some examples of the binary sensors it's not working for (config if possible) and what they look like in the feed?

**Comment by dummptyhummpty** [comment]
![Screen Shot 2019-07-23 at 9 05 15 AM](https://user-images.githubusercontent.com/13294526/61729802-e8f44680-ad2c-11e9-8196-15a7a31296cc.png)
![Screen Shot 2019-07-23 at 9 34 05 AM](https://user-images.githubusercontent.com/13294526/61729864-0b865f80-ad2d-11e9-9d21-efb692799e60.png)
Here's what I'm seeing. The config is done by a component so I have nothing to share for that.

**Comment by gadgetchnnel** [comment]
When you selected the 0.2.8b2 version, did you definitely click the Upgrade button (the button on the left in this screenshot)?

![Screenshot 2019-07-23 at 18 51 58](https://user-images.githubusercontent.com/2099542/61735075-1b2c9500-ad7b-11e9-82bd-c804e0ee7939.png)

I don't have any actual door sensors, but I have a template binary sensor with device_class set as "door" and it shows in the feed as Open or Closed when I set it to on or off.

**Comment by dummptyhummpty** [comment]
I uninstalled and reinstalled and it’s working now. Sorry about that. Thanks!
