### ISSUE TITLE
show entity title

### ISSUE THREAD

**Issue by 0xygen8** [gadgetchnnel/lovelace-home-feed-card#52]
In the current dev version (0.4.9) I have the following issue
I have made several state cards and in the latest version of HA (115) I see the following issue with titles of entities:
![Screenshot 2020-09-25 at 11 19 36](https://user-images.githubusercontent.com/10128000/94250468-8e064280-ff21-11ea-9f6b-cbcbdb284a28.png)
when I then open the notifications (from HA) the titles are presented again
![Screenshot 2020-09-25 at 11 19 59](https://user-images.githubusercontent.com/10128000/94250581-b4c47900-ff21-11ea-9968-023874649f9e.png)
is there an option to make the latter state permanent (with titles)

**Comment by gadgetchnnel** [comment]
Closing this, as I believe this was due to an old issue which has since been fixed. Please open a new issue if you are still having problems with this.
