### ISSUE TITLE
FR - Hide icons

### ISSUE THREAD

**Issue by gw1gw1** [gadgetchnnel/lovelace-home-feed-card#68]
I have very narrow columns in my dashboard and in order to save as much as possible, would it be possible to add an option to hide all icons from a feed. Result below

![image](https://user-images.githubusercontent.com/47014001/115914395-2b066b00-a472-11eb-9e2b-b8febf028065.png)

PS : Great job with this feed card !! Congrats !!

**Comment by gadgetchnnel** [comment]
This has now been implemented in the latest version, 0.6.1, via the **show_icons** setting. This defaults to true and using `show_icons: false` will hide the icons from the feed.

**Comment by gw1gw1** [comment]
Awesome. Thanks for change.
