### ISSUE TITLE
Request:  Support timestamp

### ISSUE THREAD

**Issue by manonstreet** [gadgetchnnel/lovelace-home-feed-card#7]
New feature request:  Display timestamp (optionally) instead of elapsed time.

In some situations, it would more advantageous to show exact timestamps.  For example, when binary devices change state multiple times (such as a door opening and closing) and you need to determine the time elapsed between the events, it's not possible to do with the current implementation looking at the feed once the event is over 1 hour.

**Comment by gadgetchnnel** [comment]
This should now be supported in the latest beta (0.2.9b1). You can now use the format option under an entity, the same as with the **entities** card. Setting this to datetime will display the date and time.

**Comment by manonstreet** [comment]
Works great.  Thanks.
