### ISSUE TITLE
Display broke on latest core-2021.6.0b0

### ISSUE THREAD

**Issue by bschatzow** [gadgetchnnel/lovelace-home-feed-card#70]
With the home-feed-card my display is blank.  No changes in any of my configuration.  I can see my display loading and then it goes to a blank screen.  Tried the latest chrome as well as edge.  The same on three different computers as well as phone and tablets.

my card code is:
  -

    type: "custom:home-feed-card"
    calendars:
      - 
        calendar.bschatzow_gmail_com
    id_filter: ^home_feed_.*
    more_info_on_tap: true
    entities:

      - 
        content_template: '{{display_name}} arrived at {{state}} ({{latitude}},{{longitude}})'
        entity: device_tracker.bill_pixel_gps
        name: Bill
        include_history: true
        keep_latest: true
      - 
        entity: cover.west
        include_history: true
        keep_latest: true
        remove_repeats: true
      - 
        entity: cover.middle
        exclude_states: 'off'
        include_history: true
        keep_latest: true
    title: Activity
    
  - 
    type: 'custom:home-feed-card'
    title: My_Calendar_Home_Feed
    show_empty: false
    calendars:
      - calendar.bschatzow_gmail_com
    id_filter: ^home_feed_.*

Loading any of these fail on my test lovelace display.

**Comment by gadgetchnnel** [comment]
I've published a new beta of this, 0.6.0b1, which uses an embedded lit-element to avoid this issue.
Can you please give that a go and let me know if it works for you?

**Comment by bschatzow** [comment]
Tried it. No difference.

**Comment by gadgetchnnel** [comment]
I was able to reproduce your issue in version 0.5.0 of the card but not in the 0.6.0b1 beta version.
Are you definitely on the beta version?
Maybe try clearing the browser cache, in case the old version is hanging around.

**Comment by bschatzow** [comment]
It is working now.  I was on .5 but had a HA update on the beta.  Not sure if this is what fixed it or your code.  I thought I cleared the cache, but maybe not.

**Comment by verstrepeng** [comment]
I had the same issue after upgrade to latest Home Assistant.
Upgrade of home-feed-card to beta 0.6.0b1 and cache clear solved it.

**Comment by tmchow** [comment]
I'm still seeing the same issue even with 0.6.0b1 installed.

In my dev console I see this error:

>lovelace-home-feed-card.js:227 Uncaught TypeError: Cannot read property 'querySelectorAll' of null
    at HTMLElement.set hass [as hass] (lovelace-home-feed-card.js:227)
    at HTMLElement.value (chunk.53899b0337677dfbe7ab.js:2246)
    at HTMLElement.value (chunk.53899b0337677dfbe7ab.js:2246)
    at HTMLElement.t.addEventListener.once (chunk.53899b0337677dfbe7ab.js:2246)
    at i (app.bcb38ac1.js:13497)
    at chunk.f877794aa8421b754491.js:2416

**Comment by gadgetchnnel** [comment]
Closing as I have now promoted 0.6.0 containing this fix from beta to release.
