### ISSUE TITLE
Feature to add version number to the console

### ISSUE THREAD

**Issue by kaizersoje** [gadgetchnnel/lovelace-home-feed-card#74]
Is it possible to add the version number to the console?

```
console.info(
    `%c  Home-Feed \n%c  Version ${CARD_VERSION}    `,
    'color: orange; font-weight: bold; background: black',
    'color: white; font-weight: bold; background: dimgray',
);
```
It will make to easier to understand which version of the card is in the cache, similar to the screenshot below.

![image](https://user-images.githubusercontent.com/54566217/123254635-3fc6b400-d532-11eb-9f7e-7825d12741e9.png)

**Comment by gadgetchnnel** [comment]
Thanks, I've added this to the latest version 0.6.2
