### ISSUE TITLE
Request: Make entries in the feed entity objects

### ISSUE THREAD

**Issue by manonstreet** [gadgetchnnel/lovelace-home-feed-card#9]
The entries in the feed are non-clickable.  It would be great if the entries linked to the actual entities such that when they are clicked, they behave like an entity card where the history timeline is shown.  Additionally, the icons in the feed could be overridable similar to an entity card.

**Comment by gadgetchnnel** [comment]
I have just release an updated beta, 0.2.9b2, which include a new option, **more_info_on_tap** to display the more-info popup when you click an entity in the list.

Icons for entities should already be overridable, it uses the same sort of method as the entities card, something like this:

```
type: 'custom:home-feed-card'
id_filter: ^home_feed_.*
entities:
  - entity: sensor.people_at_home
     name : People at Home
     icon: 'mdi:home'
  - entity: binary_sensor.front_door
     name: Front Door
     icon: 'mdi:door'
```

The only icons which aren't overridable are the ones for notifications, which always use the bell icon, and those for calendar events, which always use a calendar icon. I'll consider adding options to allow these to be overridden.

**Comment by gadgetchnnel** [comment]
Closing this now, as the more-info support has been added. If you still have issues with overriding icons, please raise a new issue with more details (including the version you are using, configuration, and screenshots if possible).

**Comment by manonstreet** [comment]
more_info_on_tap works great, thanks.  I'll open a separate issue regarding icons.
